apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage